<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Nine1.NMQ.Dashboard.Core\Nine1.NMQ.Dashboard.Core.csproj" />
    <ProjectReference Include="..\Nine1.NMQ.Dashboard.Infrastructure\Nine1.NMQ.Dashboard.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
